package io.mq9.a2a;

import io.a2a.spec.Message;
import io.a2a.spec.Task;

/**
 * Context passed to the {@link MessageHandler} for each incoming message.
 *
 * <p>Mirrors Python's {@code RequestContext}. The executing agent reads
 * {@code taskId} and {@code message} to process the request, then pushes
 * response events to the {@link EventQueue}.
 */
public final class A2AContext {

    /** Task ID generated by this agent (executor side) for the current request. */
    public final String taskId;

    /** Context/session ID, carried from the incoming message if present. */
    public final String contextId;

    /** The incoming A2A message. */
    public final Message message;

    /**
     * Existing task if this is a continuation of a multi-turn conversation;
     * {@code null} for a new task.
     */
    public final Task currentTask;

    A2AContext(String taskId, String contextId, Message message, Task currentTask) {
        this.taskId = taskId;
        this.contextId = contextId;
        this.message = message;
        this.currentTask = currentTask;
    }
}
